// Menu Data
export const menuCategories = [
  { id: "meat", name: "مشويات" },
  { id: "flafel", name: "فلافل" },
  { id: "drinks", name: "مشروبات" },
  { id: "dessert", name: "حلويات" },
];

// menu items
export const menuItems = [
  {
    id: 1,
    category: "meat",
    name: "سيبرية أفاشي لحم عادي",
    description: "سيبرية أفاشي لحم عادي بطعم شهي",
    price: 15,
    image: "/images/menue/1.jpg",
  },
  {
    id: 2,
    category: "meat",
    name: "سيبرية أفاشي لحم حراق",
    description: "سيبرية أفاشي لحم حراق بطعم لاذع",
    price: 18,
    image: "/images/menue/1.jpg",
  },
  {
    id: 3,
    category: "meat",
    name: "سيبرية أفاشي لحم مدفون",
    description: "سيبرية أفاشي لحم مدفون مع تتبيلة خاصة",
    price: 20,
    image: "/images/menue/1.jpg",
  },
  {
    id: 4,
    category: "meat",
    name: "سيبرية أفاشي لحم جبن",
    description: "سيبرية أفاشي لحم بالجبن المميز",
    price: 24,
    image: "/images/menue/1.jpg",
  },
  {
    id: 5,
    category: "meat",
    name: "سيبرية أفاشي دجاج عادي",
    description: "سيبرية أفاشي دجاج عادي بطعم شهي",
    price: 15,
    image: "images/menue/2.jpg",
  },
  {
    id: 6,
    category: "meat",
    name: "سيبرية أفاشي دجاج حراق",
    description: "سيبرية أفاشي دجاج حراق بطعم لاذع",
    price: 18,
    image: "images/menue/2.jpg",
  },
  {
    id: 7,
    category: "meat",
    name: "سيبرية أفاشي دجاج مدفون",
    description: "سيبرية أفاشي دجاج مدفون مع تتبيلة خاصة",
    price: 20,
    image: "images/menue/2.jpg",
  },
  {
    id: 8,
    category: "meat",
    name: "سيبرية أفاشي دجاج جبن",
    description: "سيبرية أفاشي دجاج بالجبن المميز",
    price: 24,
    image: "images/menue/2.jpg",
  },
  {
    id: 9,
    category: "meat",
    name: "شيبة لحم",
    description: "شيبة لحم بقري طازج",
    price: 25,
    image: "images/menue/3.jpg",
  },
  {
    id: 10,
    category: "meat",
    name: "كبدة",
    description: "كبدة لذيذة ومطهية بعناية",
    price: 24,
    image: "images/menue/4.jpg",
  },
  {
    id: 11,
    category: "flafel",
    name: "مصقع",
    description: "مصقع بلذيذ بنكهة تقليدية",
    price: 10,
    image: "/images/menue/5.jpg",
  },
  {
    id: 12,
    category: "flafel",
    name: "بيض طوة",
    description: "بيض طوة مقلي طازج",
    price: 7,
    image: "/images/menue/6.jpg",
  },
  {
    id: 13,
    category: "flafel",
    name: "بيض شكشوكة",
    description: "بيض شكشوكة بالبهارات الشرقية",
    price: 7,
    image: "/images/menue/7.jpg",
  },
  {
    id: 14,
    category: "flafel",
    name: "زبادي مصلح",
    description: "زبادي مع التوابل والخضروات",
    price: 7,
    image: "/images/menue/8.jpg",
  },
  // {
  //   id: 15,
  //   category: "bread",
  //   name: "بلدي كسرة",
  //   description: "خبز بلدي كسرة طازج",
  //   price: 10,
  //   image:
  //     "https://images.unsplash.com/photo-1512058564366-c9e5eeab4061?q=80&w=2075",
  // },
  {
    id: 16,
    category: "meat",
    name: "قراصة دمعة",
    description: "قراصة دمعة مع حساء لذيذ",
    price: 15,
    image: "/images/menue/9.jpg",
  },
  {
    id: 17,
    category: "meat",
    name: "لحمة صاج",
    description: "لحمة صاج مشوية على الفحم",
    price: 20,
    image: "/images/menue/10.jpg",
  },
  {
    id: 18,
    category: "meat",
    name: "ضلوع",
    description: "ضلوع مشوية بالتوابل السودانية",
    price: 35,
    image: "/images/menue/11.jpg",
  },
  {
    id: 19,
    category: "flafel",
    name: "قيمة بطاطس",
    description: "قيمة بطاطس بطعم شهي",
    price: 10,
    image: "/images/menue/12.jpg",
  },
  {
    id: 20,
    category: "flafel",
    name: "مصقع (سلطة اسود)",
    description: "مصقع مع سلطة سودانية",
    price: 10,
    image: "/images/menue/13.jpg",
  },
  {
    id: 21,
    category: "meat",
    name: "فاصوليا",
    description: "فاصوليا شهية",
    price: 10,
    image: "/images/menue/14.jpg",
  },
  {
    id: 22,
    category: "meat",
    name: "محشي",
    description: "محشي بالخضروات الطازجة",
    price: 10,
    image: "/images/menue/15.jpg",
  },
  {
    id: 23,
    category: "meat",
    name: "رجلة",
    description: "رجلة بنكهة سودانية",
    price: 10,
    image: "/images/menue/16.jpg",
  },
  {
    id: 24,
    category: "meat",
    name: "إدام مشكل",
    description: "إدام مشكل مميز",
    price: 12,
    image: "/images/menue/17.jpg",
  },
  {
    id: 25,
    category: "dessert",
    name: "عصيدة سودانية",
    description: "عصيدة سودانية بطعم فريد",
    price: 10,
    image: "/images/menue/18.jpg",
  },
  {
    id: 26,
    category: "meat",
    name: "فتة سادة (عسل)",
    description: "فتة سادة مع العسل",
    price: 10,
    image: "/images/menue/19.jpg",
  },
  {
    id: 27,
    category: "meat",
    name: "فتة تمر وسمن وعسل",
    description: "فتة تمر مع سمن وعسل",
    price: 12,
    image: "/images/menue/20.jpg",
  },

  {
    id: 28,
    category: "meat",
    name: "زقني لحم",
    description: "طبق لحم زقني سوداني أصيل",
    price: 20,
    image: "/images/menue/21.jpg",
  },
  {
    id: 29,
    category: "meat",
    name: "زقني دجاج",
    description: "طبق زقني دجاج بتوابل شهية",
    price: 20,
    image: "/images/menue/22.jpg",
  },
  {
    id: 30,
    category: "meat",
    name: "كوارع",
    description: "كوارع سودانية مطهية على الطريقة التقليدية",
    price: 20,
    image: "/images/menue/23.jpg",
  },
  {
    id: 31,
    category: "flafel",
    name: "فول سادة",
    description: "فول سادة لذيذ بالطريقة السودانية",
    price: 5,
    image: "/images/menue/24.jpg",
  },
  {
    id: 32,
    category: "flafel",
    name: "فول مصلح",
    description: "فول مع التوابل والخضروات",
    price: 7,
    image: "/images/menue/25.jpg",
  },
  {
    id: 33,
    category: "flafel",
    name: "عدس",
    description: "عدس مطهي بالتوابل الشرقية",
    price: 7,
    image: "/images/menue/26.jpg",
  },
  {
    id: 34,
    category: "flafel",
    name: "فتة فول",
    description: "فتة فول سودانية لذيذة",
    price: 10,
    image: "/images/menue/27.jpg",
  },
  {
    id: 35,
    category: "flafel",
    name: "فلافل",
    description: "فلافل محضرة بالحمص الطازج",
    price: 1,
    image: "/images/menue/28.jpg",
  },
  {
    id: 36,
    category: "flafel",
    name: "خبز بلدي",
    description: "خبز بلدي طازج ومقرمش",
    price: 1,
    image: "/images/menue/29.jpg",
  },
  {
    id: 37,
    category: "flafel",
    name: "كسرة سودانية",
    description: "كسرة سودانية تقليدية",
    price: 1,
    image: "/images/menue/31.jpg",
  },
  //! مشروبات ادريس
  {
    id: 38,
    category: "drinks",
    name: "عصير جي كاس",
    description: "عصير جي كاس",
    price: 5,
    image: "/images/menue/30.jpg",
  },
  {
    id: 39,
    category: "drinks",
    name: "عصير جي جك",
    description: "عصير جي جك",
    price: 15,
    image: "/images/menue/32.jpg",
  },
  {
    id: 40,
    category: "drinks",
    name: "عصير كركدي كاس",
    description: "عصير كركدي كاس",
    price: 5,
    image: "/images/menue/33.jpg",
  },
  {
    id: 41,
    category: "drinks",
    name: "عصير كركدي جك",
    description: "عصير كركدي جك",
    price: 15,
    image: "/images/menue/34.jpg",
  },
  {
    id: 42,
    category: "dessert",
    name: "مديده دخن كاس",
    description: "مديده دخن كاس",
    price: 5,
    image: "/images/menue/35.jpg",
  },
  {
    id: 43,
    category: "dessert",
    name: "مديده دخن جك",
    description: "مديده دخن جك",
    price: 15,
    image: "/images/menue/36.jpg",
  },
  {
    id: 44,
    category: "dessert",
    name: "معصوب قشطه",
    description: "معصوب قشطه",
    price: 10,
    image: "/images/menue/37.jpg",
  },
  {
    id: 45,
    category: "dessert",
    name: " معصوب قشطه و عسل",
    description: "معصوب قشطه و عسل",
    price: 12,
    image: "/images/menue/38.jpg",
  },
  {
    id: 46,
    category: "dessert",
    name: " معصوب سمن و عسل",
    description: "معصوب سمن و عسل",
    price: 12,
    image: "/images/menue/39.jpg",
  },
  {
    id: 47,
    category: "dessert",
    name: " معصوب سمن و قشطه",
    description: "معصوب سمن و قشطه",
    price: 12,
    image: "/images/menue/40.jpg",
  },
  {
    id: 48,
    category: "dessert",
    name: " معصوب ساده",
    description: "معصوب ساده",
    price: 8,
    image: "/images/menue/41.jpg",
  },
  {
    id: 49,
    category: "dessert",
    name: " معصوب ملكي",
    description: "معصوب ملكي",
    price: 15,
    image: "/images/menue/42.jpg",
  },
  {
    id: 50,
    category: "dessert",
    name: " معصوب ديلكوز",
    description: "معصوب ديلكوز",
    price: 17,
    image: "/images/menue/43.jpg",
  },
  {
    id: 51,
    category: "dessert",
    name: " معصوب بالحليب",
    description: "معصوب بالحليب",
    price: 10,
    image: "/images/menue/44.jpg",
  },
  {
    id: 52,
    category: "dessert",
    name: "عريكه طبقات",
    description: "عريكه طبقات",
    price: 17,
    image: "/images/menue/45.jpg",
  },
  {
    id: 53,
    category: "dessert",
    name: "عريكه عادي",
    description: "عريكه عادي",
    price: 15,
    image: "/images/menue/46.jpg",
  },
  {
    id: 54,
    category: "dessert",
    name: "عريكه ديلكوز",
    description: "عريكه ديلكوز",
    price: 17,
    image: "/images/menue/47.jpg",
  },
];

// Testimonials Data
export const testimonials = [
  {
    id: 1,
    name: "أحمد محمد",
    comment: "أفضل مطعم سوداني في المنطقة، الطعم رائع والخدمة ممتازة",
    image:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2787",
    rating: 5,
  },
  {
    id: 2,
    name: "عبدالله علي",
    comment: "الكباب عندهم لا يُعلى عليه، والأسعار معقولة جداً",
    image:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2940",
    rating: 5,
  },
  {
    id: 3,
    name: "سارة أحمد",
    comment: "جربت البرجر السوداني وكان لذيذ جداً، أنصح الجميع بتجربته",
    image:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=2940",
    rating: 4,
  },
];

// Restaurant Info
export const restaurantInfo = {
  name: "سيريه حوش ادريس",
  description:
    "نقدم أشهى المأكولات السودانية الأصيلة في المملكة العربية السعودية منذ عام ٢٠١٠. نحن نفخر بتقديم أطباق تجمع بين الأصالة والجودة العالية.",
  about:
    "مطعم سيريه حوش ادريس هو وجهتك المثالية لتذوق أشهى وألذ المأكولات السودانية الأصيلة. نحن نقدم تجربة طعام فريدة تجمع بين النكهات التقليدية والجودة العالية في أجواء مريحة وودية.",
  location: {
    address: "6144 طريق المطار، 3698، طارع المطار، جازان 82723",
    coordinates: {
      lat: 24.7136,
      lng: 46.6753,
    },
  },
  contact: {
    phone: "966501011560+",
    whatsapp: "966501011560+",
    email: "edris@mail.com",
  },
  hours: {
    weekdays: "١٢:٠٠ م - ١٢:٠٠ ص",
    weekends: "١:٠٠ م - ١:٠٠ ص",
  },
  owner: {
    name: "ادريس السودانس",
    position: "المؤسس والمدير التنفيذي",
    image: "/images/about.jpg",
    quote: "نسعى دائماً لتقديم أفضل تجربة طعام سودانية أصيلة لضيوفنا الكرام",
  },
};
